In [1]:
import numpy as np

In [5]:
array1 = np.array([1,2,5,7,8,9,10])

print(array1[3:5])

[7 8]


In [8]:
print(array1[2:50:3])

[5 9]


In [9]:
print(array1[3:])

[ 7  8  9 10]


In [10]:
print(array1[:])

[ 1  2  5  7  8  9 10]


In [11]:
numbers = np.array([1,2,3,4,5,6,7,8,9,20])
print("Before:",numbers)
numbers[3:] = 20

print("After",numbers)

Before: [ 1  2  3  4  5  6  7  8  9 20]
After [ 1  2  3 20 20 20 20 20 20 20]


In [13]:
numbers = np.array([1,2,3,4,5,6,7,8,9,20])
print("Before:",numbers)
numbers[2:50] = 20
print("After:",numbers)

Before: [ 1  2  3  4  5  6  7  8  9 20]
After: [ 1  2 20 20 20 20 20 20 20 20]


# Negative Indexing

In [14]:
numbers = [2,4,6,8,10,12]

print(numbers[-3:])

[8, 10, 12]


In [15]:
print(numbers[-5:-2])

[4, 6, 8]


In [16]:
print(numbers[-1::-2])

[12, 8, 4]


In [17]:
print(numbers[-1::-1])

[12, 10, 8, 6, 4, 2]


# 2D Numpy array slicing

In [18]:
arr = np.array([[1,3,5,7],[9,11,13,15]])

In [19]:
arr.shape

(2, 4)

In [20]:
print(arr[:2,:2])

[[ 1  3]
 [ 9 11]]


In [26]:
print(arr[:1,:])

[[1 3 5 7]]


In [28]:
print(arr[1,0])

9


In [30]:
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3d.shape

(3, 3)

In [31]:
print(arr_3d[:2,:2])

[[1 2]
 [4 5]]


In [33]:
print(arr_3d[:2,:2])

[[1 2]
 [4 5]]


In [34]:
print(arr_3d[1:50,2:4])

[[6]
 [9]]


In [37]:
arr = np.array([[[0, 1], 
             [2, 3]], 
 
            [[4, 5], 
             [6, 7]]])

In [40]:
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
arr.shape

(2, 2, 2)

In [41]:
print(arr[:, 0:,:1])

[[[0]
  [2]]

 [[4]
  [6]]]


In [42]:
x =np.arange(15)

In [43]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
x.shape = (3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
x =np.arange(15)
print("Before:",x)
print("Before shape",x.shape)
x.shape = (1,3,5)
print("\n")
print("After:",x)
print("After shape",x.shape)

Before: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Before shape (15,)


After: [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
After shape (1, 3, 5)


In [46]:
x[:-1]

array([], shape=(0, 3, 5), dtype=int32)

In [47]:
x.shape = (3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
x[:-1]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
b= np.arange(11,21).reshape(2,5)
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [59]:
a*b

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [62]:
np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

In [63]:
a.shape[1] == b.shape[0]

False

In [64]:
b = b.T

In [68]:
b

array([[11, 16],
       [12, 17],
       [13, 18],
       [14, 19],
       [15, 20]])

In [65]:
a.shape[1] == b.shape[0]

True

In [67]:
print(a.shape,b.shape)

(2, 5) (5, 2)


In [66]:
a@b

array([[205, 280],
       [530, 730]])

In [83]:
mat = np.arange(1,21).reshape(2,10)

In [84]:
mat

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [85]:
n = 4
reshaped_arr = mat.reshape(4,-1)

In [86]:
9reshaped_arr.shape

(4, 5)

In [88]:
mat.shape = (1,2,10)

In [89]:
mat

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]])

In [90]:
mat.shape

(1, 2, 10)

# Numpy argsort and other aggregation

In [92]:
arr = np.array([3,1,4,2,5])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 4 5]


In [93]:
np.mean(arr)

3.0

In [2]:
arr = np.array([3,1,4,2,5])
#sorted = 1,2,3,4,5
print(np.argsort(arr))
#This basically return the indices of numbers when the original array is sorted

[1 3 0 2 4]


# Vectorization

In [94]:
a= np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
def custom_function(x):
    if x %2== 0:
        return -x
    else:
        return x

In [97]:
print(custom_function(a))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [98]:
vectorized_function = np.vectorize(custom_function)

In [99]:
print(vectorized_function(a))

[[  1  -2   3  -4]
 [  5  -6   7  -8]
 [  9 -10  11 -12]]


In [100]:
vectorized_function(2)

array(-2)

# Concept of masking

This will help us filter the array based on a condition

In [28]:
data = np.array([10,131,20,40,111,112])

k = 10

mask = data%k == 0

In [4]:
mask

array([ True, False,  True,  True, False, False])

In [5]:
filtered_data = data[mask]
filtered_data

array([10, 20, 40])

In [6]:
#Step 1 create a mask for your filter
#step 2 check the mask for correct boolean values
#step 3 apply the mask on index within original array to get filtered data

In [64]:
data = np.array([10,131,20,40,111,112,125,145,168])

mask_10_5 = (data%5==0) | (data%10==0) 

In [65]:
data

array([ 10, 131,  20,  40, 111, 112, 125, 145, 168])

In [66]:
mask_10_5

array([ True, False,  True,  True, False, False,  True,  True, False])

In [67]:
fil_data_10_5 = data[mask_10_5]
fil_data_10_5

array([ 10,  20,  40, 125, 145])

In [34]:
data = np.array([[1.75,70],[1.60,65],[1.80,90],[1.70,75],[1.85,100]])
data.shape

(5, 2)

In [35]:
height = data[:,0]
weight = data[:,1]

print(height)
print("\n")
print(weight)

[1.75 1.6  1.8  1.7  1.85]


[ 70.  65.  90.  75. 100.]


In [36]:
bmi = weight/(height**2)
bmi

array([22.85714286, 25.390625  , 27.77777778, 25.95155709, 29.2184076 ])

In [37]:
underweight = bmi < 18.5
normalweight = (bmi >= 18.5) & (bmi < 24.9)
overweight = (bmi >= 25) & (bmi < 29.9)
obese = bmi >= 30

In [44]:
bmi[overweight]

array([25.390625  , 27.77777778, 25.95155709, 29.2184076 ])

In [45]:
classfication = np.where(underweight,"Under Weight",np.where(normalweight,"Normal",np.where(overweight,"Over weight","Obese")))

In [46]:
classfication

array(['Normal', 'Over weight', 'Over weight', 'Over weight',
       'Over weight'], dtype='<U12')

# Deep copy and Shallow Copy

In [68]:
import numpy as np
import copy

x = np.array([10,20,30,40])
#Shallow
x_view1 = x.view()
x_view2 = x[:]

In [69]:
#Deep
x_copy1 = x.copy()
x_copy2 = copy.copy(x)

In [70]:
#Before change
print(x)
print("\n")
print(x_view1)
print("\n")
print(x_view2)

[10 20 30 40]


[10 20 30 40]


[10 20 30 40]


In [71]:
#Change same array elements to see what happens
x[0] = 555

In [72]:
#After change
print(x)
print("\n")
print(x_view1)
print("\n")
print(x_view2)

[555  20  30  40]


[555  20  30  40]


[555  20  30  40]


In [73]:
x_view1[1] = 666
x_view2[2] = 777

In [74]:
#After change
print(x)
print("\n")
print(x_view1)
print("\n")
print(x_view2)

[555 666 777  40]


[555 666 777  40]


[555 666 777  40]


In [75]:
#Before change
print(x_copy1)
print("\n")
print(x_copy2)

[10 20 30 40]


[10 20 30 40]


In [76]:
x_copy1[0] = 888
x_copy2[0] = 999

In [77]:
#After change
print(x_copy1)
print("\n")
print(x_copy2)

[888  20  30  40]


[999  20  30  40]


In [78]:
x_copy1

array([888,  20,  30,  40])

In [79]:
x_copy2

array([999,  20,  30,  40])